EXPERIMENT:
  NAME: ""
  TAG: "crld,vit,res18"
  PROJECT: "tinyimagenet200_baselines"
DATASET:
  TYPE: "tinyimagenet200_384"
  NUM_WORKERS: 16
DISTILLER:
  TYPE: "CRLD"
  TEACHER: "vit"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 100
  LR: 0.025
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crld"
CRLD:
  TEMPERATURE: 2.0
